### ISSUE TITLE
Improve restoring of aspect ratio's logic

### ISSUE THREAD

**Issue by yancmo** [nus-fboa2016-PL/PowerPointLabs#14]
Currently, the program scales the height back to 100% x 100%. This can be improved by making the restore relative to the size of the current shape. The longer side will be used first, and checked to ensure that it is still within the boundaries of the slide. If it exceeds the slide, the shorter side will be used. 
For instance, a shape with 90% x 20% will be resized to 90% x 90% if the new shape does not exceed the boundaries of the slide. Otherwise, 20% x 20% will be used.

**Comment by youthinkk** [comment]
Done
