### ISSUE TITLE
Snap feature does not work well for shapes that have default direction

### ISSUE THREAD

**Issue by oswellchan** [nus-fboa2016-PL/PowerPointLabs#17]
Current implementation uses the rules of horizontal = width > height and vice versa for vertical. When images are square, results are not satisfying due to shapes having default direction. 
![image](https://cloud.githubusercontent.com/assets/8565916/12864663/4e4ec382-cccd-11e5-8d78-8e616346b28d.png)

**Comment by vhazali** [comment]
Fixed by f89afe1d3e6b505868e365594f86aa9d4967502b
