### ISSUE TITLE
Remove build action on PositionsLab.png

### ISSUE THREAD

**Issue by kai33** [nus-fboa2016-PL/PowerPointLabs#34]
here
https://github.com/nus-fboa2016-PL/PowerPointLabs/blob/MergeResizePositions/PowerPointLabs/PowerPointLabs/PowerPointLabs.csproj#L1244

right click on that image resource, and change build action to none
@oswellchan

**Comment by oswellchan** [comment]
Okay. Sorry I forgot to push that change into the merge branch for dev release. Do I wait for the next dev release to submit a PR for this?

**Comment by kai33** [comment]
just wait for next dev release
