### ISSUE TITLE
Toggle for align slide/ reference shape

### ISSUE THREAD

**Issue by vhazali** [nus-fboa2016-PL/PowerPointLabs#5]
For second round of mockup presentation, one of the feedback for align was "to include all original functions of powerpoint"
There's a function which allows the user to decide to align to shapes, or to the slide. 
Do we want to enable a toggle which lets user to decide to align to reference shape(s) or to the slide?

**Comment by oswellchan** [comment]
yes

**Comment by vhazali** [comment]
Got it, I'll add in the toggle UI later.

**Comment by vhazali** [comment]
Fixed by e248483434d33a75ffee88bc67e50c8012fb6dde for Align
Fixed by 49800029914a3c0a88ac0a794e1bcb686b09a099 for Distribute
